name: MooLego UI
author: moolego
category: Interface
tags: [moolego, ui, user interface, components, canvas, toolkit]
docs: http://ui.moolego.org/docs/
demo: http://ui.moolego.org/demos/
#current: 0.3