name: MooLego UI
author:
    - moolego
    - Jerome Vial   
    - Luca Pilonel
category: Interface
tags: [ui, user interface, components, canvas, toolkit]
docs: http://ui.moolego.net/docs/
demo: http://ui.moolego.net/demos/
#current: 0.2